spring.application.name=device-service

server.port=8082

spring.rabbitmq.host=${RABBITMQ_HOST:rabbitmq}
spring.rabbitmq.port=5672
spring.rabbitmq.username=user
spring.rabbitmq.password=pass

app.rabbitmq.exchange=device.exchange
app.rabbitmq.routing-key=device.commands