@startuml
!include ../C4_Context.puml
!include ../C4_Container.puml

LAYOUT_WITH_LEGEND()

title Warm house company context diagram

Person(user, "Warm House company user", "Remotely controls the house systems")

System_Boundary(c0, "Warm House System") {
    Container(web_app, "Web Application", "Java, Spring", "Handles user interactions")
    Container(heating_control_service, "Heating control service", "Go", "Controls heating")
    Container(light_control_service, "Light control service", "Python", "Controls light")
    Container(gate_control_service, "Gate control service", "Java", "Controls gates")
    Container(device_management_service, "Device management", "Go", "Adding, changing and deleting of devices")
    Container(telemetry_service, "Telemetry", "Python", "Telemetry receiving")
    ContainerDb(database, "Database", "PostgreSQL", "Stores user data")

'    System(warmhouse_system, "Warm House System", "Allows users to remotely control the heating in the house and check the temperature.")
'    System_Ext(warmhouse_device, "Temperature sensors", "Temperature monitoring devices")
}

Container_Ext(heating_devices, "External heating devices")

Rel_Down(user, web_app, "Requests", "HTTP")
Rel_Down(web_app, heating_control_service, "Process heating control requests")
Rel_Down(web_app, light_control_service, "Process light control requests")
Rel_Down(web_app, gate_control_service, "Process gate control requests")
Rel_Down(web_app, device_management_service, "Process managing requests")
Rel_Down(web_app, telemetry_service, "Process telemetry requests")
Rel_Left(heating_control_service, heating_devices, "Outer heating control requests")
Rel_Down(device_management_service, database, "Reads/Writes user data", "SQL")
'Rel_Neighbor(warmhouse_system, warmhouse_device, "Requests", "HTTP")

@enduml