@startuml
!include ../C4_Component.puml

title Component Diagram: Smart Device Service

Container(device_service, "Smart Device Service", "Java", "Scenario execution")

System_Boundary(orchestrator_boundary, "Device Service") {
    Component(api, "REST API", "Spring MVC", "API for scenario management")
    Component(engine, "Rules Engine", "Java", "Scenario execution")
    Component(dispatcher, "Dispatcher", "Java", "Command dispatching")
}

ContainerQueue(message_broker, "Asynchronous Event Bus", "RabbitMQ", "External broker")

Rel(api, engine, "Manages scenarios", "")
Rel(engine, dispatcher, "Sends commands", "")

Rel(message_broker, engine, "Triggers rules", "AMQP")
Rel(dispatcher, message_broker, "Publishes commands", "AMQP")
@enduml